apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: gcr.io/axial-trail-378611/flaskvol:v4
        volumeMounts:
         - name: my-pv
           mountPath: /usr
        env:
          - name: filepath
            valueFrom:
              configMapKeyRef:
                name: config
                key: filepath
      volumes:
      - name: my-pv
        persistentVolumeClaim:
            claimName: test-pvc 

    
