apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: gcr.io/axial-trail-378611/flaskvol:v4
    volumeMounts:
    - name: my-pv
      mountPath: /usr
  volumes:
  - name: my-pv
    persistentVolumeClaim:
      claimName: test-pvc
