apiVersion: apps/v1
kind: Deployment
metadata:
  name: readingfile-deployment
  labels:
    app: readingfile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readingfile
  template:
    metadata:
      labels:
        app: readingfile
    spec:
      containers:
        - name: readingfile
          image: bugscleaners/readingfile
          volumeMounts:
            - name: sqlite-volume
              mountPath: /usr/db
          ports:
            - containerPort: 8080
          env:
            - name: filepath
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: filepath
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc