apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: gcr.io/axial-trail-378611/msflaskvol:v4
        
    
        volumeMounts:
        - name: sari
          mountPath: /home/sari
        env:
          - name: filepath2
            valueFrom:
              configMapKeyRef:
                name: config
                key: filepath2
      volumes:
       - name: sari
         configMap:
          name: config
          items: 
          - key: filecontent
            path: data.txt
